import java.util.Date;

class Main {
    public static void main(String[] args) {
        Student person_one = new Student("William",  "1234905", new Date());
        Discent discent_new = new Discent("John", "1234905", new Date());
        Employe employe_new = new Employe("Pedro", "312330", new Date());
        Strin novo = new 
        System.out.println(new String(person_one.toString()));
        System.out.println(new String(discent_new.toString()));
        System.out.println(new String(employe_new.toString()));
    }

}